services:
  mongodb:
    image: mongo:4.4
    container_name: atip-mongodb
    ports:
      - "27017:27017"
    networks:
      - elk-network
    volumes:
      - mongo-data:/data/db
    environment:
      # Creds for the Web UI (added by Team Lead for local access) 
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password123

  mongo-express:
    image: mongo-express:latest
    container_name: atip-mongo-gui
    ports:
      - "8081:8081"
    networks:
      - elk-network
    depends_on:
      - mongodb
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=password123
      - ME_CONFIG_MONGODB_SERVER=mongodb
      - ME_CONFIG_BASICAUTH_USERNAME=admin
      - ME_CONFIG_BASICAUTH_PASSWORD=password123

  # Elasticsearch: The Search & Analytics Engine
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.12.0
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      # DEV SETUP ONLY: Disabling X-Pack security and SSL to simplify initial multi-module local integration
      - xpack.security.enabled=false
      - xpack.security.http.ssl.enabled=false
      # JVM Resource Optimization: Caps heap memory at 512MB to prevent OOM/crashes inside local VMs or resource-constrained dev environments 
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    ports:
      - "9200:9200"
    networks:
      - elk-network
    volumes:
      - es_data:/usr/share/elasticsearch/data

  # Logstash: The Data Processing Pipeline
  logstash:
    image: docker.elastic.co/logstash/logstash:8.12.0
    container_name: logstash
    volumes:
      - ./logstash/pipeline:/usr/share/logstash/pipeline
    environment:
      - LS_JAVA_OPTS=-Xms1g -Xmx1g
      - MONGO_USER=${MONGO_USERNAME} # Left side: Container variable | Right side: .env variable
      - MONGO_PASS=${MONGO_PASSWORD}
    networks:
      - elk-network
    depends_on:
      - elasticsearch
      - mongodb

  # Kibana: The Visualization Dashboard
  kibana:
    image: docker.elastic.co/kibana/kibana:8.12.0
    container_name: kibana
    ports:
      - "5601:5601"
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    networks:
      - elk-network
    depends_on:
      - elasticsearch

networks:
  elk-network:
    driver: bridge

volumes:
  mongo-data:
  es_data:
