input {
  mongodb {
    # 1. Database name fixed to threat_intel
    uri => 'mongodb://${MONGO_USER}:${MONGO_PASS}@mongodb:27017/threat_intel?authSource=admin'
    placeholder_db_dir => '/opt/logstash-mongodb/'
    placeholder_db_name => 'logstash_sqlite.db'
    # 2. Collection name fixed to indicators
    collection => 'indicators'
    batch_size => 5000
  }
}

filter {
  mutate {
    rename => { "_id" => "mongo_id" }
  }
}

output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "threat-intel-logs-%{+YYYY.MM.dd}"
  }
  stdout { codec => rubydebug }
}