input {
  mongodb {
    # 1. Database name fixed to threat_intel
    uri => 'mongodb://${MONGO_USER}:${MONGO_PASS}@atip-mongodb:27017/threat_intel?authSource=admin'
    placeholder_db_dir => '/opt/logstash-mongodb/'
    placeholder_db_name => 'logstash_sqlite.db'
    # 2. Collection name fixed to indicators
    collection => 'indicators'
    batch_size => 5000
  }
}

filter {
  mutate {
    rename => { "_id" => "mongo_id" }
  }
  if [mongo_id] {
    if [mongo_id][$oid] {
      mutate {
        add_field => { "indicator_id" => "%{[mongo_id][$oid]}" }
      }
    } else {
      mutate {
        add_field => { "indicator_id" => "%{mongo_id}" }
      }
    }
  }
  mutate {
    remove_field => [ "mongo_id" ]
  }

  # TYPE CONVERSION: Normalize custom threat metrics to integers.
  # By default, Elasticsearch may auto-map these incoming fields as strings.
  # Forcing them to integers ensures we can perform mathematical operations, 
  # score distributions, and numeric aggregations (like histograms) in Kibana.
  mutate {
    convert => {
      "risk_score"    => "integer"
      "vt_malicious"  => "integer"
      "vt_harmless"   => "integer"
    }
  }
}

output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "threat-intel-indicators-%{+YYYY.MM.dd}"
    document_id => "%{indicator_id}"
  }
  stdout { codec => rubydebug }
}
